version: "3"
services:
  jellyfin:
    image: "docker.io/jellyfin/jellyfin:latest"
    user: 1002:1002
    group_add:
      - 998
    volumes:
      - jellyfin-cache:/cache
      - jellyfin-config:/config
      - /data/hdd/JAV:/media
      - /data/hdd/Videos/MV:/MV
      - /data/hdd/Share/Fonts/:/usr/share/fonts/truetype/dejavu/
      - /data/hdd/Videos/Shows/:/Shows/
      - /data/hdd/Videos/Movies/:/Movies/
      - ./certbot/conf/:/etc/letsencrypt/
    devices:
      # VAAPI Devices (examples)
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    ports:
      - 6908:8096
    networks:
      - jellyfin-net

  nginx:
    image: "docker.io/library/nginx:latest"
    ports:
      - 8096:8096
      - 8920:8920
    volumes:
      - ./nginx/jellyfin.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/8718248_www.juminhee.com.pem:/etc/ssl/certs/8718248_www.juminhee.com.pem
      - ./nginx/8718248_www.juminhee.com.key:/etc/ssl/private/8718248_www.juminhee.com.key
    networks:
      - jellyfin-net

volumes:
  jellyfin-cache:
    name: jellyfin-cache
    external: true
  jellyfin-config:
    name: jellyfin-config
    external: true

networks:
  jellyfin-net:
